import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import esbuild from 'esbuild';
import {
  BROWSER_BUNDLE,
  GENERATED_ASSETS,
  GENERATED_DIR,
  STYLESHEET,
  root,
  sharedAliases,
} from './assets.mjs';
import { resolve } from 'node:path';

/**
 * Builds the two assets a converted presentation carries: the shared
 * Terminalogue stylesheet, and the browser runtime that mounts the shared
 * renderer into the placeholders Marp wrote.
 *
 * Both end up as string constants in `src/generated/assets.ts` so the engine
 * can be bundled into one self-contained file — a presentation must work with
 * no network and no `node_modules` anywhere near it.
 */

const bundle = await esbuild.build({
  entryPoints: [resolve(root, 'src/browser/main.ts')],
  outfile: BROWSER_BUNDLE,
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  minify: true,
  sourcemap: false,
  alias: sharedAliases,
  logLevel: 'warning',
  write: true,
});

if (bundle.errors.length > 0) process.exit(1);

const script = readFileSync(BROWSER_BUNDLE, 'utf8');
const css = readFileSync(STYLESHEET, 'utf8');

// Both strings are written straight into a `<script>` and a `<style>` element,
// so neither may contain a sequence that could close its own element early.
assertInert(script, /<\/script/i, 'the browser runtime', '</script');
assertInert(script, /<!--/, 'the browser runtime', '<!--');
assertInert(css, /<\/style/i, 'the stylesheet', '</style');

mkdirSync(GENERATED_DIR, { recursive: true });
writeFileSync(
  GENERATED_ASSETS,
  `/*
 * Generated by scripts/generate-assets.mjs. Do not edit.
 *
 * TERMINALOGUE_CSS is packages/renderer/src/terminalogue.css verbatim, and
 * TERMINALOGUE_BROWSER_SCRIPT is the bundled browser runtime, so a converted
 * presentation needs no network access at all.
 */

/** The shared Terminalogue stylesheet, byte for byte. */
export const TERMINALOGUE_CSS: string = ${JSON.stringify(css)};

/** The self-contained browser runtime, as an IIFE. */
export const TERMINALOGUE_BROWSER_SCRIPT: string = ${JSON.stringify(script)};
`,
  'utf8',
);

console.log(
  `[terminalogue-marp] assets -> ${GENERATED_ASSETS} ` +
    `(css ${css.length} B, runtime ${script.length} B)`,
);
mkdirSync(dirname(BROWSER_BUNDLE), { recursive: true });

function assertInert(text, pattern, what, sequence) {
  if (pattern.test(text)) {
    console.error(`[terminalogue-marp] ${what} contains "${sequence}" and cannot be inlined.`);
    process.exit(1);
  }
}
